AWSTemplateFormatVersion: '2010-09-09'
Description: Serverless Frontend CI/CD

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket

  # S3 BUCKETS
  b1S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: b1-s3-bucket
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - HEAD
              - GET
            AllowedOrigins:
              - '*'
  b1S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref b1S3Bucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${b1S3Bucket}/*"

  b2S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: b2-s3-bucket
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - HEAD
              - GET
            AllowedOrigins:
              - '*'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:Put"
            Function: !GetAtt indexPhotosLambda.Arn
  b2S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref b2S3Bucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${b2S3Bucket}/*"

  # LAMBDA Functions
  searchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Search Photos Lambda Function"
      FunctionName: search-photos-new
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt AllLambdaRole.Arn
      Runtime: python3.9
      Timeout: 30
      Code:
        S3Bucket: photolambda
        S3Key: search-photos.zip

  indexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: "Index Photos Lambda Function"
      FunctionName: index-photos-new
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt AllLambdaRole.Arn
      Runtime: python3.9
      Timeout: 30
      Code:
        S3Bucket: photolambda
        S3Key: index-photos.zip

  indexPhotosLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt indexPhotosLambda.Arn
      Principal: "s3.amazonaws.com"
      SourceArn: !GetAtt b2S3Bucket.Arn

  # IAM Role
  AllLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "AllLambdaCombinedPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:*"
                  - "s3-object-lambda:*"
                  - "rekognition:*"
                  - "es:*"
                  - "cloudwatch:GetMetricStatistics"
                  - "cloudwatch:DescribeAlarms"
                  - "cloudwatch:DescribeAlarmsForMetric"
                  - "kms:DescribeKey"
                  - "kms:ListAliases"
                  - "lambda:GetPolicy"
                  - "lambda:ListFunctions"
                  - "lex:*"
                  - "polly:DescribeVoices"
                  - "polly:SynthesizeSpeech"
                  - "kendra:ListIndices"
                  - "iam:ListRoles"
                  - "s3:ListAllMyBuckets"
                  - "logs:DescribeLogGroups"
                  - "s3:GetBucketLocation"
                  - "lambda:AddPermission"
                  - "lambda:RemovePermission"
                  - "iam:GetRole"
                  - "iam:CreateServiceLinkedRole"
                  - "iam:DeleteServiceLinkedRole"
                  - "iam:GetServiceLinkedRoleDeletionStatus"
                  - "iam:PassRole"
                Resource: "*"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonRekognitionFullAccess"
        - "arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess"
        - "arn:aws:iam::aws:policy/AmazonLexFullAccess"
